version: '3.7'

services:
  fhir:
    image: hapiproject/hapi:latest
    ports:
      - "8090:8080"
    volumes:
      - fhir-data:/data/hapi
    environment:
      hapi.fhir.fhir_version: "R5"
      hapi.fhir.tester.home.fhir_version: "R5"
      hapi.fhir.subscription.resthook_enabled: "true"
      hapi.fhir.subscription.email.from: "test@test.test"
      hapi.fhir.subscription.email.host: "test.test"

volumes:
  fhir-data:
