edition = "2024"
hard_tabs = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 100
wrap_comments = true
comment_width = 100
doc_comment_code_block_width = 100
format_code_in_doc_comments = true
use_small_heuristics = "Max"
blank_lines_upper_bound = 2
spaces_around_ranges = true
