comment_width = 80
doc_comment_code_block_width = 80
edition = "2021"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
max_width = 100
use_small_heuristics = "Max"
wrap_comments = true
