services:
  hapi-r5:
    image: hapiproject/hapi:latest
    ports:
      - "8100:8080"
    environment:
      hapi.fhir.server_address: "http://localhost:8100/fhir"
      hapi.fhir.fhir_version: "R5"
      hapi.fhir.tester.home.fhir_version: "R5"
      hapi.fhir.subscription.resthook_enabled: "true"
      spring.datasource.url: "jdbc:postgresql://postgres:5432/hapi_r5"
      spring.datasource.username: "fhir"
      spring.datasource.password: "password"
      spring.datasource.driverClassName: "org.postgresql.Driver"
      spring.jpa.properties.hibernate.dialect: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect"
      # For some reason needed to start the server?
      hapi.fhir.subscription.email.from: "test@test.test"
      hapi.fhir.subscription.email.host: "test.test"
      spring.main.allow-bean-definition-overriding: "true"
    depends_on:
      postgres:
        condition: service_healthy
