version: "3.7"

services:
  fhir:
    image: hapiproject/hapi:latest
    ports:
      - "8090:8080"
    volumes:
      - hapi-r5-db:/data/hapi
    environment:
      hapi.fhir.fhir_version: "R5"
      hapi.fhir.tester.home.fhir_version: "R5"
      hapi.fhir.subscription.resthook_enabled: "true"
      # For some reason needed to start the server?
      hapi.fhir.subscription.email.from: "test@test.test"
      hapi.fhir.subscription.email.host: "test.test"

volumes:
  hapi-r5-db:
