version: "3.7"

services:
  medplum-r4:
    image: medplum/medplum-server:latest
    volumes:
      - ./medplum/config-r4.json:/usr/src/medplum/packages/server/medplum.config.json
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
