//! Resource definitions.

#[rustfmt::skip] // Too much for rustfmt
#[allow(clippy::doc_lazy_continuation)] // Comments from FHIR spec.
mod generated;

pub use generated::*;

use crate::identifiable_resource::identifiable_resource_code;

identifiable_resource_code!(
	stu3,
	[
		Account,
		ActivityDefinition,
		AllergyIntolerance,
		Appointment,
		AppointmentResponse,
		Basic,
		BodySite,
		CarePlan,
		CareTeam,
		Claim,
		ClaimResponse,
		ClinicalImpression,
		Communication,
		CommunicationRequest,
		Condition,
		Coverage,
		DataElement,
		Device,
		DeviceRequest,
		DeviceUseStatement,
		DiagnosticReport,
		DocumentManifest,
		DocumentReference,
		EligibilityRequest,
		EligibilityResponse,
		Encounter,
		Endpoint,
		EnrollmentRequest,
		EnrollmentResponse,
		EpisodeOfCare,
		ExplanationOfBenefit,
		FamilyMemberHistory,
		Flag,
		Goal,
		Group,
		HealthcareService,
		ImagingStudy,
		Immunization,
		ImmunizationRecommendation,
		Library,
		List,
		Location,
		Measure,
		Media,
		MedicationAdministration,
		MedicationDispense,
		MedicationRequest,
		MedicationStatement,
		NutritionOrder,
		Observation,
		Organization,
		Patient,
		PaymentNotice,
		PaymentReconciliation,
		Person,
		PlanDefinition,
		Practitioner,
		PractitionerRole,
		Procedure,
		ProcedureRequest,
		ProcessRequest,
		ProcessResponse,
		Questionnaire,
		ReferralRequest,
		RelatedPerson,
		RequestGroup,
		ResearchStudy,
		Schedule,
		Sequence,
		ServiceDefinition,
		Slot,
		Specimen,
		StructureDefinition,
		StructureMap,
		Substance,
		Task,
		ValueSet,
		VisionPrescription,
	]
);
