[package]
authors = ["Flix <felix.dommes@rwth-aachen.de>"]
categories = ["data-structures", "parser-implementations", "web-programming"]
description = "FHIR SDK Models."
documentation = "https://docs.rs/fhir-sdk"
edition = "2021"
exclude = ["/tests/*-examples-json"]
homepage = "https://github.com/FlixCoder/fhir-sdk"
keywords = ["FHIR", "JSON", "types"]
license = "MIT"
name = "fhir-model"
readme = "README.md"
repository = "https://github.com/FlixCoder/fhir-sdk"
version = "0.4.1"

[features]
default = ["r5", "builders"]
builders = ["dep:typed-builder"]
r4b = []
r5 = []

[dependencies]
serde = {version = "1.0.158", features = ["derive"]}
typed-builder = {version = "0.16.0", optional = true}

[dev-dependencies]
assert-json-diff = "2.0.2"
serde_json = "1.0.94"

[package.metadata.docs.rs]
features = ["r5", "builders"]
no-default-features = true
